<a href="https://colab.research.google.com/github/RafsanJany-44/Machine-School/blob/main/Con_Fusion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:

data = 'https://raw.githubusercontent.com/RafsanJany-44/Thesis_Project/main/All_DATA/without_sn_and_Epoch/EEG_HMC.csv'
dataset = pd.read_csv(data)

In [3]:
X = dataset.iloc[:, 1:].values
y = dataset.iloc[:, 0].values

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 0)

In [5]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train =sc.fit_transform(X_train)

X_test =sc.fit_transform(X_test)

In [6]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=20, random_state=0)
classifier.fit(X_train, y_train)
y_pred=classifier.predict(X_test)

#Hare the Main Section

In [7]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))

[[ 1287  1120    24   428  1048]
 [  452 10894   767   354   504]
 [   21  1684  5153     8   141]
 [  443  1341    47  3470   212]
 [  461   232    12    44  5642]]
              precision    recall  f1-score   support

          N1       0.48      0.33      0.39      3907
          N2       0.71      0.84      0.77     12971
          N3       0.86      0.74      0.79      7007
           R       0.81      0.63      0.71      5513
           W       0.75      0.88      0.81      6391

    accuracy                           0.74     35789
   macro avg       0.72      0.68      0.69     35789
weighted avg       0.74      0.74      0.73     35789

Accurecy:  0.7389421330576434
