<a href="https://colab.research.google.com/github/RafsanJany-44/Machine-School/blob/main/K_fold_CV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Libraries

In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import pandas as pd
import matplotlib.pyplot as plt
data = 'https://raw.githubusercontent.com/RafsanJany-44/Machine-School/main/datasets/HMC_WITH_BIOM.csv'

dataset = pd.read_csv(data)


#Spliting

In [17]:
X = dataset.iloc[:, 1:].values
y = dataset.iloc[:, 0].values


from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 0)


**Logistic Regression**

In [4]:
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.33447149643705465

**SVM**

In [5]:
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.7357482185273159

**Random Forest**

In [6]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.7902315914489311

<h2 style='color:purple'>KFold cross validation</h2>

**Basic example**

In [7]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [8]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


**Use KFold Manuaaly

In [18]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [52]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for t,d in folds.split(X,y):
  print(t,d)

'''for train_index, test_index in folds.split(X,y):
    X_train, X_test, y_train, y_test = X[train_index], y[test_index], \
                                       X[train_index], [test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))'''

[ 5662  5930  5931 ... 20407 20408 20409] [    0     1     2 ... 10344 10345 10346]
[    0     1     2 ... 20407 20408 20409] [ 5662  5930  5931 ... 16234 16235 16236]
[    0     1     2 ... 16234 16235 16236] [11421 11422 11423 ... 20407 20408 20409]


"for train_index, test_index in folds.split(X,y):\n    X_train, X_test, y_train, y_test = X[train_index], y[test_index],                                        X[train_index], [test_index]\n    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  \n    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))\n    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))"

In [ ]:
scores_logistic

[0.8953488372093024, 0.9499165275459098, 0.9093959731543624]

In [ ]:
scores_svm

[0.39368770764119604, 0.41068447412353926, 0.4597315436241611]

In [ ]:
scores_rf

[0.9285714285714286, 0.9515859766277128, 0.9295302013422819]

<h2 style='color:purple'>cross_val_score function</h2>

In [11]:
from sklearn.model_selection import cross_val_score

**Logistic regression model performance using cross_val_score**

In [12]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X, y,cv=3)

array([0.33788948, 0.23768925, 0.33779215])

**svm model performance using cross_val_score**

In [ ]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=3)

array([0.39368771, 0.41068447, 0.45973154])

**random forest performance using cross_val_score**

In [ ]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)

array([0.93521595, 0.94156928, 0.93288591])

cross_val_score uses stratifield kfold by default

<h2 style='color:purple'>Parameter tunning using k fold cross validation</h2>

In [ ]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.8793698637138034

In [ ]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)

0.9358915527370766

In [ ]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores3)

0.9494121957589801

In [ ]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)

0.9482877777434258

Here we used cross_val_score to
fine tune our random forest classifier and figured that having around 40 trees in random forest gives best result. 