<a href="https://colab.research.google.com/github/RafsanJany-44/Machine-School/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#TENSORS
Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other specialized hardware to accelerate computing. If you’re familiar with ndarrays, you’ll be right at home with the Tensor API. If not, follow along in this quick API walkthrough.

In [2]:
import torch
import numpy as np

#Tensor Initialization
Tensors can be initialized in various ways. Take a look at the following examples:
<br><br>
<b>Directly from data</b>

Tensors can be created directly from data. The data type is automatically inferred.



In [3]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [4]:
x_data

tensor([[1, 2],
        [3, 4]])

#From a NumPy array

Tensors can be created from NumPy arrays (and vice versa - see Bridge with NumPy).

In [5]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [7]:
np_array

array([[1, 2],
       [3, 4]])

In [6]:
x_np

tensor([[1, 2],
        [3, 4]])

#From another tensor:

The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.

In [8]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7034, 0.1596],
        [0.3863, 0.0154]]) 

